# mvn clean install -DskipTests

version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: springboot-eureka-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../mongo-db:/data/db

  db:
    image: mysql
    container_name: springboot-eureka-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-db:/var/lib/mysql
