# mvn clean install -DskipTests

version: '3.1'

services:
  db:
    image: mysql
    container_name: springboot-eureka-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-db:/var/lib/mysql
